# -*- coding: utf-8 -*-
"""Task 04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jISb8JDpAoZJQ96FIMlFx645d333t-us
"""

# Task 4
# read the file
input_file = open("input4.txt","r")
# generate a output file by running the code
output_file = open("output4.txt","w")

# read the array size
N = int(input_file.readline())
# read the array
array = input_file.readline().split(" ")
array = list(map(int, array))     # Convert ['1','2'] to [1,2]

def findMax(arr):                                  # Merge Sort
  if len(arr) <= 1:
    return arr, int(arr[0])
  else:
    mid = len(arr) // 2
    left, max_value = findMax(arr[:mid])
    right, max_value = findMax(arr[mid:])
    merged, max_value = CheckAndMerge(left, right, max_value)
    return merged, max_value

def CheckAndMerge(left, right, max_value):        # Merge
  i = 0
  j = 0
  while i < len(left) and j < len(right):
    exp = left[i] + right[j]*right[j]
    max_value = max(max_value, exp)
    if left[i] <= right[j]:
      i += 1
    else:
      j += 1
  return left+right, max_value


sorted, max = findMax(array)

# Write Output
output_file.write(str(max))

# # Must Close the file
output_file.close()