# -*- coding: utf-8 -*-
"""Task 02.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jISb8JDpAoZJQ96FIMlFx645d333t-us
"""

# Task 2

# read the file
input_file = open("input2.txt","r")
# generate a output file by running the code
output_file = open("output2.txt","w")

# read the array size
N = int(input_file.readline())
# read the array
array = input_file.readline().split(" ")
array = list(map(int, array))     # Convert ['1','2'] to [1,2]

# Divide and conquer to find Maximum element of a list

def find_max(array, left, right):
  if left == right:
    return array[left]
  else:
    mid = (left+right)//2
    left_max = find_max(array, left, mid)
    right_max = find_max(array, mid+1, right)
    return left_max if left_max > right_max else right_max

left = 0
right = N-1

# Write Output
output_file.write(str(find_max(array, left, right)))

# Must Close the file
output_file.close()