# -*- coding: utf-8 -*-
"""Task 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jISb8JDpAoZJQ96FIMlFx645d333t-us
"""

# Task 1

# read the file
input_file = open("input1.txt","r")
# generate a output file by running the code
output_file = open("output1.txt","w")

# read the array size
N = int(input_file.readline())
# read the array
array = input_file.readline().split(" ")
array = list(map(int, array))     # Convert ['1','2'] to [1,2]

def merge(a, b):
  merged = []
  i = 0
  j = 0
  while i < len(a) and j < len(b):
    if a[i] <= b[j]:
      merged.append(a[i])
      i += 1
    else:
      merged.append(b[j])
      j += 1
  merged.extend(a[i:])
  merged.extend(b[j:])
  return merged


def mergeSort(arr):
  if len(arr) <= 1:
    return arr
  else:
    mid = len(arr)// 2
    a1 = mergeSort(arr[:mid])
    a2 = mergeSort(arr[mid:])
    return merge(a1, a2)


sorted = list(map(str, mergeSort(array)))
output_file.write(" ".join(str(num) for num in mergeSort(sorted)))

# Must Close the file
output_file.close()