# -*- coding: utf-8 -*-
"""Task 05.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jISb8JDpAoZJQ96FIMlFx645d333t-us
"""

# Task 5

# read the file
input_file = open("input5.txt","r")
# generate a output file by running the code
output_file = open("output5.txt","w")

# read the array size
N = int(input_file.readline())
# read the array
array = input_file.readline().split(" ")
array = list(map(int, array))     # Convert ['1','2'] to [1,2]


def quicksort(a, p, r):        # (a,p,r) ~ (array, low, high)
  if p < r:
    q = partition(a, p, r)     # q = pivot index
    quicksort(a, p, q-1)
    quicksort(a, q+1, r)
  return array

def partition(a, p, r):
  x = a[r]
  i = p-1
  for j in range(p, r, 1):
    if a[j] < x:
      i += 1
      a[i], a[j] = a[j], a[i]
  a[i+1], a[r] = a[r], a[i+1]
  return i+1

# Write Output
output_file.write(" ".join(str(num) for num in quicksort(array, 0, N-1)))    #quicksort(array,low,high)

# # Must Close the file
output_file.close()