# -*- coding: utf-8 -*-
"""Task 06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jISb8JDpAoZJQ96FIMlFx645d333t-us
"""

# Task 6

# read the file
input_file = open("input6.txt","r")
# generate a output file by running the code
output_file = open("output6.txt","w")

# read the array size
N = int(input_file.readline()[0])
# read the array
array = input_file.readline().split(" ")
array = list(map(int, array))     # Convert ['1','2'] to [1,2]
# read the query
Q = int(input_file.readline()[0])


def partition(a, p, r):           # Using the Partition Function of Task 5
  x = a[r]
  i = p-1
  for j in range(p, r, 1):
    if a[j] < x:
      i += 1
      a[i], a[j] = a[j], a[i]
  a[i+1], a[r] = a[r], a[i+1]
  return i+1

def find_Kth_Smallest(a, k):
  p = 0
  r = len(a)-1
  while p <= r:
    pivot_idx = partition(a, p, r)
    if pivot_idx == k-1:
      return a[pivot_idx]
    elif pivot_idx > k-1:
      r = pivot_idx-1
    else:
      p = pivot_idx+1
  return None

for i in range(Q):
  K = int(input_file.readline())
  smallest_num = find_Kth_Smallest(array, K)
  output_file.write(str(smallest_num)+"\n")

# # Must Close the file
output_file.close()