# -*- coding: utf-8 -*-
"""Task 01 [Parrt-02].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jISb8JDpAoZJQ96FIMlFx645d333t-us
"""

## Task 1 (part-2)   [2 pointer Technique - Applicable for sorted array]

# read the file
f = open("input1.txt","r")
# generate a output file by running the code
f2 = open("output1.txt","w")

# read the array size
N,S = map(int,f.readline().split(" "))

# read the array
array = f.readline().split(" ")
array = list(map(int, array))     # Convert ['1','2'] to [1,2]

flag = False

for i in range(N):
  if array[i] + array[N-1] == S:
    f2.write(str(i+1)+" "+ str(N))      # Code for output file
    flag = True
    break

if flag == False:
  f2.write("IMPOSSIBLE")          # Code for output file

# Must Close the file
f2.close()