# -*- coding: utf-8 -*-
"""Task 01 [Parrt-01].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jISb8JDpAoZJQ96FIMlFx645d333t-us
"""

## Task 1 (part-1)   [n^2 means 2 loop]

# read the file
f = open("input1.txt","r")
# generate a output file by running the code
f2 = open("output1.txt","w")

# read the array size
N,S = map(int,f.readline().split(" "))

# read the array
array = f.readline().split(" ")
array = list(map(int, array))     # Convert ['1','2'] to [1,2]

flag = False

for i in range(N):
  if flag == False:
    for j in range(i+1,N):
      if array[i] + array[j] == S:
        f2.write(str(i+1)+" "+ str(j+1))      # Code for output file
        flag = True
        break
  else:
    break

if flag == False:
  f2.write("IMPOSSIBLE")          # Code for output file

# Must Close the file
f2.close()