# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jISb8JDpAoZJQ96FIMlFx645d333t-us
"""

# Task 3

f1 = open('input3.txt', 'r')
f2 = open('output3.txt', 'w')

# read file
N,K = map(int, f1.readline().split())

djset = []

for _ in range(K):
    a,b = map(int, f1.readline().split())

    di1 = -1
    di2 = -1
    c = 0

    for i in range(len(djset)):
        if a in djset[i]:
            di1 = i
        elif b in djset[i]:
            di2 = i

    # if not part of any existing disjoint sets
    if di1 == -1 and di2 == -1:
        djset.append(set({a,b}))
        c = 2
    elif di1 != di2 and di1 != -1 and di2 != -1: # if two separate djsets exists, merge them
        djset[di1] = djset[di1].union(djset[di2]) # build union func
        c = len(djset[di1])
        djset.remove(djset[di2])
    elif di1 == -1:
        djset[di2].add(a)
        c = len(djset[di2])
    elif di2 == -1:
        djset[di1].add(b)
        c = len(djset[di1])

    #write output file
    f2.write(str(c)+"\n")


f1.close()
f2.close()