# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jISb8JDpAoZJQ96FIMlFx645d333t-us
"""

# Task 2

import heapq

def dijkstra(graph, source):
    distances = {vertex: float('inf') for vertex in graph}
    distances[source] = 0
    priority_queue = [(0, source)]

    while priority_queue:
        current_distance, current_vertex = heapq.heappop(priority_queue)

        if current_distance > distances[current_vertex]:
            continue

        for neighbor, weight in graph[current_vertex]:
            distance = current_distance + weight
            if distance < distances[neighbor]:
                distances[neighbor] = distance
                heapq.heappush(priority_queue, (distance, neighbor))

    return distances


f1 = open('input2.txt', 'r')
f2 = open('output2.txt', 'w')

N,M = map(int, f1.readline().split())

G = {}

for i in range(N+1):
    G[i] = []

for i in range(M):
    s,d,w = map(int, f1.readline().split())
    G[s].append((d,w))

s,t = map(int, f1.readline().split())

dS = dijkstra(G, s)
dT = dijkstra(G, t)

min_time = float('inf')
Meet = None

for v in range(1, N + 1):
    if dS[v] != float('inf') and dT[v] != float('inf'):
        t = max(dS[v] , dT[v])
        if t < min_time:
            min_time = t
            Meet = v

if Meet == None or min_time == float('inf'):
    f2.write('Impossible')
else:
    f2.write(f"Time {min_time} \nNode {Meet}")

f1.close()
f2.close()