# -*- coding: utf-8 -*-
"""Task 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jISb8JDpAoZJQ96FIMlFx645d333t-us
"""

# task 03

# step1: Topological Sort
# step2: Reverse the Edges
# step3: Run DFS on reverse edges based on the previously sorted vertex

#global
stack = []

def dfs(G, v, visited, TopologicalSortEnabled=True, StrongL = None):
    visited.add(v)
    if not TopologicalSortEnabled:
        StrongL.append(v)

    for neighbour in G[v]:
        if neighbour not in visited:
            dfs(G, neighbour, visited, TopologicalSortEnabled, StrongL)

    if TopologicalSortEnabled:
        stack.append(v)


f1 = open('input3.txt', 'r')
f2 = open('output3.txt', 'w')

n,m = map(int, f1.readline().split())

D = {}
reverseG = {}
for i in range(n+1):
    D[i] = []
    reverseG[i] = []


for i in range(m):
    s,d = map(int, f1.readline().split())
    D[s].append(d)
    #graph with reverse edges
    reverseG[d].append(s)

visited = set()

# topological sort using dfs
for i in range(1,n+1):
    if i not in visited:
        dfs(D, i, visited)

visited.clear()
strong = []
while stack:
    l = []
    x = stack.pop()
    if x not in visited:
        dfs(reverseG,x,visited,TopologicalSortEnabled=False,StrongL=l)

    if l:
        strong.append(l)

#write to file
f2.write(str(strong).strip('[]').replace('], ','\n').replace('[','').replace(']','').replace(',',''))

f1.close()
f2.close()